### ISSUE TITLE
Add keyword-spacing rule

### ISSUE THREAD

**Issue by rchapman-eb** [eventbrite/javascript#79]
I want to propose adding the [keyword-spacing](https://eslint.org/docs/rules/keyword-spacing) rule to our lint config used in core-js. Actually, this rule already exists in core/eslintrc.json but now that we set `root: true` for our eslint config in core-js the linter won't cascade up to that ruleset.

**Comment by benmvp** [comment]
That (lack of) spacing has always bugged me in diffs too! It must've been an oversight on my part when creating the origin eslint configurations.

So the steps would be to create a PR to add it to our config [here](https://github.com/eventbrite/javascript/blob/master/packages/eslint-config-eventbrite-legacy/rules/style.js#L54).

Our `core-js` repo is pretty behind on our updated rules that we have in EDS. So if/when this gets approved here, you can also manually add it in `core-js`. Since this is just about spacing it should be auto-fixable, which would be 👌

**Comment by rchapman-eb** [comment]
PR opened here: #80
